In [3]:
import numpy as np

a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

print("a" , a)
print("b" , b)


a [1 2 3]
b [[1 2 3]
 [4 5 6]]


In [4]:
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Dimension of b:", b.ndim)
print("Data type of b:", b.dtype)

Shape of a: (3,)
Shape of b: (2, 3)
Dimension of b: 2
Data type of b: int64


In [7]:
print("First row of b:", b[0])
print("Element at row1,col2:", b[0,1])
print("Slice rows 0-1, col 1-2:\n", b[0:2, 1:3])


First row of b: [1 2 3]
Element at row1,col2: 2
Slice rows 0-1, col 1-2:
 [[2 3]
 [5 6]]


In [8]:
x = np.array([10,20,30])
print("b + x:\n", b + x)

b + x:
 [[11 22 33]
 [14 25 36]]


In [9]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("Dot product:", np.dot(v1, v2)) 

Dot product: 32


In [10]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
print("Matrix multiplication:\n", np.matmul(m1, m2))

Matrix multiplication:
 [[19 22]
 [43 50]]


In [ ]:
matrix = np.array([[1,2,3] , [4,5,6],[7,8,9]])

print(matrix)

transpose_matrix = matrix.T
print("This is the Transpose matrix which help to convert the ROWS and COLUMNS")

print(transpose_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
# Task 2: Generate an array from np.arange(1, 11) and reshape it into 2x5.

array_arange = np.arange(1,11)

print(array_arange)

print("")

reshaper = array_arange.reshape(2,5)

print(reshaper)

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])


square = (vector_a - vector_b)**2

D = np.sqrt(np.sum(square))

print("\nVector A:", vector_a)
print("Vector B:", vector_b)
print("Euclidean Distance:", D)


Vector A: [1 2 3]
Vector B: [4 5 6]
Euclidean Distance: 5.196152422706632
